API_KEY = 'VC9Yi6ynO6aEtkoOZlyanraCk89Q1jq5yBm2JCF0zytZOfFIBTxRJJ9JscYdAYNJ'
API_SECRET = 'WOSvETT2iuPQDjydDqPvV3rNANPd0Qgvd3vrTDUKNOMeXIyDcWG1ttcdYxyOtayX'
BASE_URL = 'https://testnet.binance.vision'
TRADE_SYMBOL = 'BTCUSDT'
TRADE_QUANTITY = 0.001